# Generated by Django 4.2.7 on 2024-02-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='adress',
            new_name='address',
        ),
    ]
